### PR TITLE
Pip installable

### PR DESCRIPTION
**Pull request by manics**
This should be pip-installable, e.g. `pip install https://github.com/ome/virtual-microscope/archive/06041c7fa2e433fad9d39466ba7b8c6ca123fb62.zip`

Sets the version to `1.0.1` for now

### CODE REVIEW

**Comment by manics** [comment]
Fixes for the Flake8 errors are in https://github.com/ome/virtual-microscope/pull/15

**Comment by mtbc** [comment]
```
pip install https://github.com/ome/virtual-microscope/archive/d2b5826a.zip
omero config append omero.web.apps '"virtualmicroscope"'
omero config set omero.web.login_redirect '{"redirect": ["webindex"], "viewname": "webindex_custom", "query_string": "", "args": []}'
omero admin start
omero web start
```
... and indeed it works as desired after login! :+1:

Maybe once you satisfy Travis we can get this merged and up to PyPI?

**Comment by mtbc** [comment]
RFE: Update `README.md`. :smiley:

**Comment by manics** [comment]
Updated

**Comment by joshmoore** [comment]
Re-opening with flake fixes merged.

**Comment by joshmoore** [comment]
Green. Merging.

**Pull request merged**
